### ISSUE TITLE
Cut a new release for iOS

### ISSUE THREAD

**Issue by jar349** [mumble-voip/mumble-iphoneos#106]
The last version of mumble available for iOS is from 2014, but it's clear that you've made updates to the codebase since then.  This is a request for you to cut a new release and upload it to the itunes store.

**Comment by mkrautz** [comment]
Yes, the app really needs a new release.

Unfortunately, all my time right now is spent getting a 1.3.0 release of desktop Mumble out the door.

Hopefully I'll get some time during the month to be able to cut a release.

Here's a checklist/braindump of the necessary steps. Any help is greatly appreciated.

If anyone is interested, I think we need to go through the various warnings we're getting with Xcode 8.3 and fix 'em. Also, we should consider deprecated APIs in the process, since we'll probably be targetting iOS 9 or 10 as the deployment target.
Also, we should check whether we need to update icons, add a .xib launch screen for big devices, etc. etc.

**Comment by wilsonlmh** [comment]
I hope for a new release too. Specially the PTT function and settings panes after connected server. I wish to help but I'm not a expert in iOS. However I can help to design the settings UI(and maybe the whole app UI). I will upload my works later.

**Comment by mkrautz** [comment]
Mumble for iOS 1.3.1 released.
