### ISSUE TITLE
iOS 11 incompatible with 32 bit apps

### ISSUE THREAD

**Issue by mkrautz** [mumble-voip/mumble-iphoneos#107]
Via https://github.com/mumble-voip/mumble/issues/3129:

iOS 10 warns that Mumble will be incompatible with future updates to iOS (because it's a 32-bit app) All iOS apps must use 64-bit architecture once iOS 11 releases in Fall 2017.

**Comment by mkrautz** [comment]
The plan is to make a new release before then. It's thoroughly needed.

**Comment by triwav** [comment]
Any update on expected release? About to start using just want to make sure it will be updated. Thanks.

**Comment by nixCodeX** [comment]
Sorry, I haven't yet had a chance to look at it

**Comment by wtmoose** [comment]
Are you still committed to an update before iOS 11 launches?

**Comment by bleightyturner** [comment]
@wtmoose and anyone else that this may effect. I was able to get this app running on iOS 11 by just recompiling it in Xcode. The only change I had to change was the bundle identifier since info.mumble.Mumble is obviously already taken. Since you can install on a device without having to have a paid member account now, this an option for those wanting to run iOS 11. Hopefully the app will get updated before then but if not at least that's an option. I did see some Int casting warnings but the app seemed to work correctly in my limited testing. Hope this helps someone.

**Comment by mkrautz** [comment]
Yes, the apps were mostly ported to 64-bit a long time ago. I still plan to have an updated version out in time for iOS 11 release.

**Comment by mkrautz** [comment]
Remaining issues (that I'm aware of):
https://github.com/mumble-voip/mumble-iphoneos/issues/110

**Comment by mkrautz** [comment]
Released 1.3.1.
